---
title: "Project Home"
site: workflowr::wflow_site
# output:
#   workflowr::wflow_html:
#     toc: false
output:
  bookdown::html_document2:
    toc: true
editor_options:
  chunk_output_type: console
  markdown: 
    wrap: 72
---

This is the website for the research project "Frequency-Aware Similarity
Calibration".

If you have cloned the project to a local computer this website is
rendered in the `docs` subdirectory of the project directory.

If you are using `workflowr` to publish the research website it will
also be rendered online to GitHub Pages.

This page acts as a table of contents for the website. There are links
to the web pages generated from the analysis notebooks and to the
rendered versions of manuscripts/documents/presentations.

------------------------------------------------------------------------

# Overview documents {.unnumbered}

## [Proposal](proposal.html) {.unnumbered}

This notebook explains the central ideas behind the project.

## [Notes](notes.html) {.unnumbered}

This notebook is for keeping notes of any points that may be useful for
later project or manuscript development and which are not covered in the
analysis notebooks or at risk of getting lost in the notebooks.

## [Workflow management](workflow.html) {.unnumbered}

This project uses the [`targets`](https://wlandau.github.io/targets/)
and [`workflowr`](https://github.com/jdblischak/workflowr) packages for
managing the workflow of the project (making sure that the dependencies
between computational steps are satisfied). When this work was started
there were no easily found examples of using `targets` and `workflowr`
together. This notebook contains notes on the proposed workflow for
using `targets` and `workflowr`.

------------------------------------------------------------------------

# Manuscripts {.unnumbered}

Links to rendered manuscripts and presentations will go here.

------------------------------------------------------------------------

# Analysis Notebooks {.unnumbered}

## 01 Read, check, and standardise the entity data {.unnumbered}

Initial data preparation of imported entity records.

### [01-1 Get, subset, check, and save data](01-1_get_data.html) {.unnumbered}

Import the raw data, cut it back to the subset of rows and columns that
are possibly useful, sanity check the data, and save the data in an
R-friendly format.

### [01-2 Check administrative variables](01-2_check_admin.html) {.unnumbered}

Check the "administrative" variables. This is data relating to the
administration of voter registration.

### [01-3 Check residence variables](01-3_check_resid.html) {.unnumbered}

Check the residence variables - residential address and phone number.

### [01-4 Check demographic variables](01-4_check_demog.html) {.unnumbered}

Check the demographic variables - sex, age, and birth place.

### [01-5 Check name variables](01-5_check_name.html) {.unnumbered}

Check the name variables.

### [01-6 Clean variables](01-6_clean_vars.html) {.unnumbered}

Clean all the variables.

------------------------------------------------------------------------

## 02 Blocking variables {.unnumbered}

Examine the distributions of potential blocking variables.

### [02-1 Characterise blocking variables](02-1_char_block_vars.html) {.unnumbered}

Characterise the potential blocking variables and combinations of
variables.

### [02-2 Make blocking variables](02-2_mk_block_vars.html) {.unnumbered}

Construct the most promising potential combination blocking variables.

------------------------------------------------------------------------

## 03 Name frequency (equality) {.unnumbered}

Detailed examination of the distributions of name frequencies induced by
the string equality relation.

------------------------------------------------------------------------

## 04 Name frequency (similarity) {.unnumbered}

Detailed examination of the distributions of name frequencies induced by
a string similarity relation.

------------------------------------------------------------------------

## 05 Similarity calibration {.unnumbered}

Detailed examination of the calibration from similarity to probability
of identity match, both unconditionally and as a function of name
frequency.

------------------------------------------------------------------------

## 06 Compatibility models {.unnumbered}

Estimate multivariate compatibility models.
